"""Chat-related Pydantic models."""
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime


class ChatMessage(BaseModel):
    """Chat message model."""
    role: str = Field(..., pattern="^(user|assistant|system)$")
    content: str


class ChatRequest(BaseModel):
    """Chat request model."""
    message: str = Field(..., min_length=1)
    conversation_id: Optional[str] = None
    include_context: bool = True
    use_graph_rag: bool = False  # opt-in: graph-first candidate set
    compare_mode: bool = False   # opt-in: structure answer as a comparison
    with_followups: bool = True  # opt-out: skip generating follow-up chips


class ChatResponse(BaseModel):
    """Chat response model."""
    message: str
    conversation_id: str
    related_chunks: List[Dict[str, Any]] = []
    related_entities: List[Dict[str, Any]] = []
    # Up to 3 follow-up question chips generated by the LLM after the
    # answer. Empty list = no followups (either opted out or the LLM
    # call failed — both are non-fatal).
    followups: List[str] = []
    # Fraction (0.0–1.0) of source chips that the answer actually
    # cites. A low value (e.g. 0.2) means the LLM mostly hand-waved
    # and the sources weren't really used. Front-end renders this as
    # a small "X% cited" indicator.
    citation_coverage: float = 0.0


class Conversation(BaseModel):
    """Conversation model."""
    id: str
    user_id: int
    title: Optional[str] = None
    created_at: datetime

    class Config:
        from_attributes = True


class SearchRequest(BaseModel):
    """Search request model."""
    query: str = Field(..., min_length=1)
    top_k: int = Field(default=5, ge=1, le=20)
    include_context: bool = True


class SearchResponse(BaseModel):
    """Search response model."""
    query: str
    chunks: List[Dict[str, Any]]
    entities: List[Dict[str, Any]]
    relations: List[Dict[str, Any]]
